using eventManagementAPI.Data;
using eventManagementAPI.Models;
using Microsoft.EntityFrameworkCore;

namespace eventManagementAPI.Seeders
{
    public static class DistrictSeeder
    {
        public static void Seed(ApplicationDbContext context)
        {
            if (!context.Districts.Any())
            {
                var districts = new List<District>
            {
              new District{code = 10101,cantonId=1,name="Carmen"},
              new District{code = 10102,cantonId=1,name="Merced"},
              new District{code = 10103,cantonId=1,name="Hospital"},
              new District{code = 10104,cantonId=1,name="Catedral"},
              new District{code = 10105,cantonId=1,name="Zapote"},
              new District{code = 10106,cantonId=1,name="San Francisco de Dos Ríos"},
              new District{code = 10107,cantonId=1,name="Uruca"},
              new District{code = 10108,cantonId=1,name="Mata Redonda"},
              new District{code = 10109,cantonId=1,name="Pavas"},
              new District{code = 10110,cantonId=1,name="Hatillo"},
              new District{code = 10111,cantonId=1,name="San Sebastián"},
              new District{code = 10201,cantonId=2,name="Escazú"},
              new District{code = 10202,cantonId=2,name="San Antonio"},
              new District{code = 10203,cantonId=2,name="San Rafael"},
              new District{code = 10301,cantonId=3,name="Desamparados"},
              new District{code = 10302,cantonId=3,name="San Miguel"},
              new District{code = 10303,cantonId=3,name="San Juan de Dios"},
              new District{code = 10304,cantonId=3,name="San Rafael Arriba"},
              new District{code = 10305,cantonId=3,name="San Antonio"},
              new District{code = 10306,cantonId=3,name="Frailes"},
              new District{code = 10307,cantonId=3,name="Patarrá"},
              new District{code = 10308,cantonId=3,name="San Cristóbal"},
              new District{code = 10309,cantonId=3,name="Rosario"},
              new District{code = 10310,cantonId=3,name="Damas"},
              new District{code = 10311,cantonId=3,name="San Rafael Abajo"},
              new District{code = 10312,cantonId=3,name="Gravilias"},
              new District{code = 10313,cantonId=3,name="Los Guido"},
              new District{code = 10401,cantonId=4,name="Santiago"},
              new District{code = 10402,cantonId=4,name="Mercedes Sur"},
              new District{code = 10403,cantonId=4,name="Barbacoas"},
              new District{code = 10404,cantonId=4,name="Grifo Alto"},
              new District{code = 10405,cantonId=4,name="San Rafael"},
              new District{code = 10406,cantonId=4,name="Candelaria"},
              new District{code = 10407,cantonId=4,name="Desamparaditos"},
              new District{code = 10408,cantonId=4,name="San Antonio"},
              new District{code = 10409,cantonId=4,name="Chires"},
              new District{code = 10501,cantonId=5,name="San Marcos"},
              new District{code = 10502,cantonId=5,name="San Lorenzo"},
              new District{code = 10503,cantonId=5,name="San Carlos"},
              new District{code = 10601,cantonId=6,name="Aserrí"},
              new District{code = 10602,cantonId=6,name="Tarbaca o Praga"},
              new District{code = 10603,cantonId=6,name="Vuelta de Jorco"},
              new District{code = 10604,cantonId=6,name="San Gabriel"},
              new District{code = 10605,cantonId=6,name="La Legua"},
              new District{code = 10606,cantonId=6,name="Monterrey"},
              new District{code = 10607,cantonId=6,name="Salitrillos"},
              new District{code = 10701,cantonId=7,name="Colón"},
              new District{code = 10702,cantonId=7,name="Guayabo"},
              new District{code = 10703,cantonId=7,name="Tabarcia"},
              new District{code = 10704,cantonId=7,name="Piedras Negras"},
              new District{code = 10705,cantonId=7,name="Picagres"},
              new District{code = 10801,cantonId=8,name="Guadalupe"},
              new District{code = 10802,cantonId=8,name="San Francisco"},
              new District{code = 10803,cantonId=8,name="Calle Blancos"},
              new District{code = 10804,cantonId=8,name="Mata de Plátano"},
              new District{code = 10805,cantonId=8,name="Ipís"},
              new District{code = 10806,cantonId=8,name="Rancho Redondo"},
              new District{code = 10807,cantonId=8,name="Purral"},
              new District{code = 10901,cantonId=9,name="Santa Ana"},
              new District{code = 10902,cantonId=9,name="Salitral"},
              new District{code = 10903,cantonId=9,name="Pozos o Concepción"},
              new District{code = 10904,cantonId=9,name="Uruca o San Joaquín"},
              new District{code = 10905,cantonId=9,name="Piedades"},
              new District{code = 10906,cantonId=9,name="Brasil"},
              new District{code = 11001,cantonId=10,name="Alajuelita"},
              new District{code = 11002,cantonId=10,name="San Josecito"},
              new District{code = 11003,cantonId=10,name="San Antonio"},
              new District{code = 11004,cantonId=10,name="Concepción"},
              new District{code = 11005,cantonId=10,name="San Felipe"},
              new District{code = 11101,cantonId=11,name="San Isidro"},
              new District{code = 11102,cantonId=11,name="San Rafael"},
              new District{code = 11103,cantonId=11,name="Dulce Nombre de Jesús"},
              new District{code = 11104,cantonId=11,name="Patalillo"},
              new District{code = 11105,cantonId=11,name="Cascajal"},
              new District{code = 11201,cantonId=12,name="San Ignacio"},
              new District{code = 11202,cantonId=12,name="Guaitil"},
              new District{code = 11203,cantonId=12,name="Palmichal"},
              new District{code = 11204,cantonId=12,name="Cangrejal"},
              new District{code = 11205,cantonId=12,name="Sabanillas"},
              new District{code = 11301,cantonId=13,name="San Juan"},
              new District{code = 11302,cantonId=13,name="Cinco Esquinas"},
              new District{code = 11303,cantonId=13,name="Anselmo Llorente"},
              new District{code = 11304,cantonId=13,name="León XIII"},
              new District{code = 11305,cantonId=13,name="Colima"},
              new District{code = 11401,cantonId=14,name="San Vicente"},
              new District{code = 11402,cantonId=14,name="San Jerónimo"},
              new District{code = 11403,cantonId=14,name="Trinidad"},
              new District{code = 11501,cantonId=15,name="San Pedro"},
              new District{code = 11502,cantonId=15,name="Sabanilla"},
              new District{code = 11503,cantonId=15,name="Mercedes o Betania"},
              new District{code = 11504,cantonId=15,name="San Rafael"},
              new District{code = 11601,cantonId=16,name="San Pablo"},
              new District{code = 11602,cantonId=16,name="San Pedro"},
              new District{code = 11603,cantonId=16,name="San Juan de Mata"},
              new District{code = 11604,cantonId=16,name="San Luis"},
              new District{code = 11605,cantonId=16,name="Cárara"},
              new District{code = 11701,cantonId=17,name="Santa María"},
              new District{code = 11702,cantonId=17,name="Jardín"},
              new District{code = 11703,cantonId=17,name="Copey"},
              new District{code = 11801,cantonId=18,name="Curridabat"},
              new District{code = 11802,cantonId=18,name="Granadilla"},
              new District{code = 11803,cantonId=18,name="Sánchez"},
              new District{code = 11804,cantonId=18,name="Tirrases"},
              new District{code = 11901,cantonId=19,name="San Isidro de el General"},
              new District{code = 11902,cantonId=19,name="General"},
              new District{code = 11903,cantonId=19,name="Daniel Flores"},
              new District{code = 11904,cantonId=19,name="Rivas"},
              new District{code = 11905,cantonId=19,name="San Pedro"},
              new District{code = 11906,cantonId=19,name="Platanares"},
              new District{code = 11907,cantonId=19,name="Pejibaye"},
              new District{code = 11908,cantonId=19,name="Cajón"},
              new District{code = 11909,cantonId=19,name="Barú"},
              new District{code = 11910,cantonId=19,name="Río Nuevo"},
              new District{code = 11911,cantonId=19,name="Páramo"},
              new District{code = 12001,cantonId=20,name="San Pablo"},
              new District{code = 12002,cantonId=20,name="San Andrés"},
              new District{code = 12003,cantonId=20,name="Llano Bonito"},
              new District{code = 12004,cantonId=20,name="San Isidro"},
              new District{code = 12005,cantonId=20,name="Santa Cruz"},
              new District{code = 12006,cantonId=20,name="San Antonio"},
              new District{code = 20101,cantonId=21,name="Alajuela"},
              new District{code = 20102,cantonId=21,name="San José"},
              new District{code = 20103,cantonId=21,name="Carrizal"},
              new District{code = 20104,cantonId=21,name="San Antonio"},
              new District{code = 20105,cantonId=21,name="Guácima"},
              new District{code = 20106,cantonId=21,name="San Isidro"},
              new District{code = 20107,cantonId=21,name="Sabanilla"},
              new District{code = 20108,cantonId=21,name="San Rafael"},
              new District{code = 20109,cantonId=21,name="Río Segundo"},
              new District{code = 20110,cantonId=21,name="Desamparados"},
              new District{code = 20111,cantonId=21,name="Turrucares"},
              new District{code = 20112,cantonId=21,name="Tambor"},
              new District{code = 20113,cantonId=21,name="La Garita"},
              new District{code = 20114,cantonId=21,name="Sarapiquí"},
              new District{code = 20201,cantonId=22,name="San Ramón"},
              new District{code = 20202,cantonId=22,name="Santiago"},
              new District{code = 20203,cantonId=22,name="San Juan"},
              new District{code = 20204,cantonId=22,name="Piedades Norte"},
              new District{code = 20205,cantonId=22,name="Piedades Sur"},
              new District{code = 20206,cantonId=22,name="San Rafael"},
              new District{code = 20207,cantonId=22,name="San Isidro"},
              new District{code = 20208,cantonId=22,name="Angeles"},
              new District{code = 20209,cantonId=22,name="Alfaro"},
              new District{code = 20210,cantonId=22,name="Volio"},
              new District{code = 20211,cantonId=22,name="Concepción"},
              new District{code = 20212,cantonId=22,name="Zapotal"},
              new District{code = 20213,cantonId=22,name="San Isidro de Peñas Blancas"},
              new District{code = 20301,cantonId=23,name="Grecia"},
              new District{code = 20302,cantonId=23,name="San Isidro"},
              new District{code = 20303,cantonId=23,name="San José"},
              new District{code = 20304,cantonId=23,name="San Roque"},
              new District{code = 20305,cantonId=23,name="Tacares"},
              new District{code = 20306,cantonId=23,name="Río Cuarto"},
              new District{code = 20307,cantonId=23,name="Puente Piedra"},
              new District{code = 20308,cantonId=23,name="Bolívar"},
              new District{code = 20401,cantonId=24,name="San Mateo"},
              new District{code = 20402,cantonId=24,name="Desmonte"},
              new District{code = 20403,cantonId=24,name="Jesús María"},
              new District{code = 20501,cantonId=25,name="Atenas"},
              new District{code = 20502,cantonId=25,name="Jesús"},
              new District{code = 20503,cantonId=25,name="Mercedes"},
              new District{code = 20504,cantonId=25,name="San Isidro"},
              new District{code = 20505,cantonId=25,name="Concepción"},
              new District{code = 20506,cantonId=25,name="San José"},
              new District{code = 20507,cantonId=25,name="Santa Eulalia"},
              new District{code = 20508,cantonId=25,name="Escobal"},
              new District{code = 20601,cantonId=26,name="Naranjo"},
              new District{code = 20602,cantonId=26,name="San Miguel"},
              new District{code = 20603,cantonId=26,name="San José"},
              new District{code = 20604,cantonId=26,name="Cirrí Sur"},
              new District{code = 20605,cantonId=26,name="San Jerónimo"},
              new District{code = 20606,cantonId=26,name="San Juan"},
              new District{code = 20607,cantonId=26,name="Rosario"},
              new District{code = 20701,cantonId=27,name="Palmares"},
              new District{code = 20702,cantonId=27,name="Zaragoza"},
              new District{code = 20703,cantonId=27,name="Buenos Aires"},
              new District{code = 20704,cantonId=27,name="Santiago"},
              new District{code = 20705,cantonId=27,name="Candelaria"},
              new District{code = 20706,cantonId=27,name="Esquipulas"},
              new District{code = 20707,cantonId=27,name="La Granja"},
              new District{code = 20801,cantonId=28,name="San Pedro"},
              new District{code = 20802,cantonId=28,name="San Juan"},
              new District{code = 20803,cantonId=28,name="San Rafael"},
              new District{code = 20804,cantonId=28,name="Carrillos"},
              new District{code = 20805,cantonId=28,name="Sabana Redonda"},
              new District{code = 20901,cantonId=29,name="Orotina"},
              new District{code = 20902,cantonId=29,name="Mastate"},
              new District{code = 20903,cantonId=29,name="Hacienda Vieja"},
              new District{code = 20904,cantonId=29,name="Coyolar"},
              new District{code = 20905,cantonId=29,name="Ceiba"},
              new District{code = 21001,cantonId=30,name="Quesada"},
              new District{code = 21002,cantonId=30,name="Florencia"},
              new District{code = 21003,cantonId=30,name="Buenavista"},
              new District{code = 21004,cantonId=30,name="Aguas Zarcas"},
              new District{code = 21005,cantonId=30,name="Venecia"},
              new District{code = 21006,cantonId=30,name="Pital"},
              new District{code = 21007,cantonId=30,name="Fortuna"},
              new District{code = 21008,cantonId=30,name="Tigra"},
              new District{code = 21009,cantonId=30,name="Palmera"},
              new District{code = 21010,cantonId=30,name="Venado"},
              new District{code = 21011,cantonId=30,name="Cutris"},
              new District{code = 21012,cantonId=30,name="Monterrey"},
              new District{code = 21013,cantonId=30,name="Pocosol"},
              new District{code = 21101,cantonId=31,name="Zarcero"},
              new District{code = 21102,cantonId=31,name="Laguna"},
              new District{code = 21103,cantonId=31,name="Tapezco"},
              new District{code = 21104,cantonId=31,name="Guadalupe"},
              new District{code = 21105,cantonId=31,name="Palmira"},
              new District{code = 21106,cantonId=31,name="Zapote"},
              new District{code = 21107,cantonId=31,name="Las Brisas"},
              new District{code = 21201,cantonId=32,name="Sarchí Norte"},
              new District{code = 21202,cantonId=32,name="Sarchí Sur"},
              new District{code = 21203,cantonId=32,name="Toro Amarillo"},
              new District{code = 21204,cantonId=32,name="San Pedro"},
              new District{code = 21205,cantonId=32,name="Rodríguez"},
              new District{code = 21301,cantonId=33,name="Upala"},
              new District{code = 21302,cantonId=33,name="Aguas Claras"},
              new District{code = 21303,cantonId=33,name="San José o Pizote"},
              new District{code = 21304,cantonId=33,name="Bijagua"},
              new District{code = 21305,cantonId=33,name="Delicias"},
              new District{code = 21306,cantonId=33,name="Dos Ríos"},
              new District{code = 21307,cantonId=33,name="Yolillal"},
              new District{code = 21401,cantonId=34,name="Los Chiles"},
              new District{code = 21402,cantonId=34,name="Caño Negro"},
              new District{code = 21403,cantonId=34,name="Amparo"},
              new District{code = 21404,cantonId=34,name="San Jorge"},
              new District{code = 21501,cantonId=35,name="San Rafael"},
              new District{code = 21502,cantonId=35,name="Buenavista"},
              new District{code = 21503,cantonId=35,name="Cote"},
              new District{code = 30101,cantonId=36,name="Oriental"},
              new District{code = 30102,cantonId=36,name="Occidental"},
              new District{code = 30103,cantonId=36,name="Carmen"},
              new District{code = 30104,cantonId=36,name="San Nicolás"},
              new District{code = 30105,cantonId=36,name="Aguacaliente o San Francisco"},
              new District{code = 30106,cantonId=36,name="Guadalupe o Arenilla"},
              new District{code = 30107,cantonId=36,name="Corralillo"},
              new District{code = 30108,cantonId=36,name="Tierra Blanca"},
              new District{code = 30109,cantonId=36,name="Dulce Nombre"},
              new District{code = 30110,cantonId=36,name="Llano Grande"},
              new District{code = 30111,cantonId=36,name="Quebradilla"},
              new District{code = 30201,cantonId=37,name="Paraíso"},
              new District{code = 30202,cantonId=37,name="Santiago"},
              new District{code = 30203,cantonId=37,name="Orosi"},
              new District{code = 30204,cantonId=37,name="Cachí"},
              new District{code = 30205,cantonId=37,name="Los Llanos de Santa Lucía"},
              new District{code = 30301,cantonId=38,name="Tres Ríos"},
              new District{code = 30302,cantonId=38,name="San Diego"},
              new District{code = 30303,cantonId=38,name="San Juan"},
              new District{code = 30304,cantonId=38,name="San Rafael"},
              new District{code = 30305,cantonId=38,name="Concepción"},
              new District{code = 30306,cantonId=38,name="Dulce Nombre"},
              new District{code = 30307,cantonId=38,name="San Ramón"},
              new District{code = 30308,cantonId=38,name="Río Azul"},
              new District{code = 30401,cantonId=39,name="Juan Viñas"},
              new District{code = 30402,cantonId=39,name="Tucurrique"},
              new District{code = 30403,cantonId=39,name="Pejibaye"},
              new District{code = 30501,cantonId=40,name="Turrialba"},
              new District{code = 30502,cantonId=40,name="La Suiza"},
              new District{code = 30503,cantonId=40,name="Peralta"},
              new District{code = 30504,cantonId=40,name="Santa Cruz"},
              new District{code = 30505,cantonId=40,name="Santa Teresita"},
              new District{code = 30506,cantonId=40,name="Pavones"},
              new District{code = 30507,cantonId=40,name="Tuis"},
              new District{code = 30508,cantonId=40,name="Tayutic"},
              new District{code = 30509,cantonId=40,name="Santa Rosa"},
              new District{code = 30510,cantonId=40,name="Tres Equis"},
              new District{code = 30511,cantonId=40,name="La Isabel"},
              new District{code = 30512,cantonId=40,name="Chirripó"},
              new District{code = 30601,cantonId=41,name="Pacayas"},
              new District{code = 30602,cantonId=41,name="Cervantes"},
              new District{code = 30603,cantonId=41,name="Capellades"},
              new District{code = 30701,cantonId=42,name="San Rafael"},
              new District{code = 30702,cantonId=42,name="Cot"},
              new District{code = 30703,cantonId=42,name="Potrero Cerrado"},
              new District{code = 30704,cantonId=42,name="Cipreses"},
              new District{code = 30705,cantonId=42,name="Santa Rosa"},
              new District{code = 30801,cantonId=43,name="El Tejar"},
              new District{code = 30802,cantonId=43,name="San Isidro"},
              new District{code = 30803,cantonId=43,name="Tobosi"},
              new District{code = 30804,cantonId=43,name="Patio de Agua"},
              new District{code = 40101,cantonId=44,name="Heredia"},
              new District{code = 40102,cantonId=44,name="Mercedes"},
              new District{code = 40103,cantonId=44,name="San Francisco"},
              new District{code = 40104,cantonId=44,name="Ulloa"},
              new District{code = 40105,cantonId=44,name="Varablanca"},
              new District{code = 40201,cantonId=45,name="Barva"},
              new District{code = 40202,cantonId=45,name="San Pedro"},
              new District{code = 40203,cantonId=45,name="San Pablo"},
              new District{code = 40204,cantonId=45,name="San Roque"},
              new District{code = 40205,cantonId=45,name="Santa Lucía"},
              new District{code = 40206,cantonId=45,name="San José de la Montaña"},
              new District{code = 40301,cantonId=46,name="Santo Domingo"},
              new District{code = 40302,cantonId=46,name="San Vicente"},
              new District{code = 40303,cantonId=46,name="San Miguel"},
              new District{code = 40304,cantonId=46,name="Paracito"},
              new District{code = 40305,cantonId=46,name="Santo Tomás"},
              new District{code = 40306,cantonId=46,name="Santa Rosa"},
              new District{code = 40307,cantonId=46,name="Tures"},
              new District{code = 40308,cantonId=46,name="Pará"},
              new District{code = 40401,cantonId=47,name="Santa Bárbara"},
              new District{code = 40402,cantonId=47,name="San Pedro"},
              new District{code = 40403,cantonId=47,name="San Juan"},
              new District{code = 40404,cantonId=47,name="Jesús"},
              new District{code = 40405,cantonId=47,name="Santo Domingo del Roble"},
              new District{code = 40406,cantonId=47,name="Puraba"},
              new District{code = 40501,cantonId=48,name="San Rafael"},
              new District{code = 40502,cantonId=48,name="San Josecito"},
              new District{code = 40503,cantonId=48,name="Santiago"},
              new District{code = 40504,cantonId=48,name="Angeles"},
              new District{code = 40505,cantonId=48,name="Concepción"},
              new District{code = 40601,cantonId=49,name="San Isidro"},
              new District{code = 40602,cantonId=49,name="San José"},
              new District{code = 40603,cantonId=49,name="Concepción"},
              new District{code = 40604,cantonId=49,name="San Francisco"},
              new District{code = 40701,cantonId=50,name="San Antonio"},
              new District{code = 40702,cantonId=50,name="La Ribera"},
              new District{code = 40703,cantonId=50,name="Asunción"},
              new District{code = 40801,cantonId=51,name="San Joaquín"},
              new District{code = 40802,cantonId=51,name="Barrantes"},
              new District{code = 40803,cantonId=51,name="Llorente"},
              new District{code = 40901,cantonId=52,name="San Pablo"},
              new District{code = 41001,cantonId=53,name="Puerto Viejo"},
              new District{code = 41002,cantonId=53,name="La Virgen"},
              new District{code = 41003,cantonId=53,name="Horquetas"},
              new District{code = 41004,cantonId=53,name="Llanuras de Gaspar"},
              new District{code = 41005,cantonId=53,name="Cureña"},
              new District{code = 50101,cantonId=54,name="Liberia"},
              new District{code = 50102,cantonId=54,name="Cañas Dulces"},
              new District{code = 50103,cantonId=54,name="Mayorga"},
              new District{code = 50104,cantonId=54,name="Nacascolo"},
              new District{code = 50105,cantonId=54,name="Curubande"},
              new District{code = 50201,cantonId=55,name="Nicoya"},
              new District{code = 50202,cantonId=55,name="Mansión"},
              new District{code = 50203,cantonId=55,name="San Antonio"},
              new District{code = 50204,cantonId=55,name="Quebrada Honda"},
              new District{code = 50205,cantonId=55,name="Sámara"},
              new District{code = 50206,cantonId=55,name="Nósara"},
              new District{code = 50207,cantonId=55,name="Belén de Nosarita"},
              new District{code = 50301,cantonId=56,name="Santa Cruz"},
              new District{code = 50302,cantonId=56,name="Bolsón"},
              new District{code = 50303,cantonId=56,name="Veintisiete de Abril"},
              new District{code = 50304,cantonId=56,name="Tempate"},
              new District{code = 50305,cantonId=56,name="Cartagena"},
              new District{code = 50306,cantonId=56,name="Cuajiniquil"},
              new District{code = 50307,cantonId=56,name="Diriá"},
              new District{code = 50308,cantonId=56,name="Cabo Velas"},
              new District{code = 50309,cantonId=56,name="Tamarindo"},
              new District{code = 50401,cantonId=57,name="Bagaces"},
              new District{code = 50402,cantonId=57,name="Fortuna"},
              new District{code = 50403,cantonId=57,name="Mogote"},
              new District{code = 50404,cantonId=57,name="Río Naranjo"},
              new District{code = 50501,cantonId=58,name="Filadelfia"},
              new District{code = 50502,cantonId=58,name="Palmira"},
              new District{code = 50503,cantonId=58,name="Sardinal"},
              new District{code = 50504,cantonId=58,name="Belén"},
              new District{code = 50601,cantonId=59,name="Cañas"},
              new District{code = 50602,cantonId=59,name="Palmira"},
              new District{code = 50603,cantonId=59,name="San Miguel"},
              new District{code = 50604,cantonId=59,name="Bebedero"},
              new District{code = 50605,cantonId=59,name="Porozal"},
              new District{code = 50701,cantonId=60,name="Juntas"},
              new District{code = 50702,cantonId=60,name="Sierra"},
              new District{code = 50703,cantonId=60,name="San Juan"},
              new District{code = 50704,cantonId=60,name="Colorado"},
              new District{code = 50801,cantonId=61,name="Tilarán"},
              new District{code = 50802,cantonId=61,name="Quebrada Grande"},
              new District{code = 50803,cantonId=61,name="Tronadora"},
              new District{code = 50804,cantonId=61,name="Santa Rosa"},
              new District{code = 50805,cantonId=61,name="Líbano"},
              new District{code = 50806,cantonId=61,name="Tierras Morenas"},
              new District{code = 50807,cantonId=61,name="Arenal"},
              new District{code = 50901,cantonId=62,name="Carmona"},
              new District{code = 50902,cantonId=62,name="Santa Rita"},
              new District{code = 50903,cantonId=62,name="Zapotal"},
              new District{code = 50904,cantonId=62,name="San Pablo"},
              new District{code = 50905,cantonId=62,name="Porvenir"},
              new District{code = 50906,cantonId=62,name="Bejuco"},
              new District{code = 51001,cantonId=63,name="La Cruz"},
              new District{code = 51002,cantonId=63,name="Santa Cecilia"},
              new District{code = 51003,cantonId=63,name="Garita"},
              new District{code = 51004,cantonId=63,name="Santa Elena"},
              new District{code = 51101,cantonId=64,name="Hojancha"},
              new District{code = 51102,cantonId=64,name="Monte Romo"},
              new District{code = 51103,cantonId=64,name="Puerto Carrillo"},
              new District{code = 51104,cantonId=64,name="Huacas"},
              new District{code = 60101,cantonId=65,name="Puntarenas"},
              new District{code = 60102,cantonId=65,name="Pitahaya"},
              new District{code = 60103,cantonId=65,name="Chomes"},
              new District{code = 60104,cantonId=65,name="Lepanto"},
              new District{code = 60105,cantonId=65,name="Paquera"},
              new District{code = 60106,cantonId=65,name="Manzanillo"},
              new District{code = 60107,cantonId=65,name="Guacimal"},
              new District{code = 60108,cantonId=65,name="Barranca"},
              new District{code = 60109,cantonId=65,name="Monte Verde"},
              new District{code = 60110,cantonId=65,name="Isla del Coco"},
              new District{code = 60111,cantonId=65,name="Cóbano"},
              new District{code = 60112,cantonId=65,name="Chacarita"},
              new District{code = 60113,cantonId=65,name="Chira"},
              new District{code = 60114,cantonId=65,name="Acapulco"},
              new District{code = 60115,cantonId=65,name="Roble"},
              new District{code = 60116,cantonId=65,name="Arancibia"},
              new District{code = 60201,cantonId=66,name="Espíritu Santo"},
              new District{code = 60202,cantonId=66,name="San Juan Grande"},
              new District{code = 60203,cantonId=66,name="Macacona"},
              new District{code = 60204,cantonId=66,name="San Rafael"},
              new District{code = 60205,cantonId=66,name="San Jerónimo"},
              new District{code = 60301,cantonId=67,name="Buenos Aires"},
              new District{code = 60302,cantonId=67,name="Volcán"},
              new District{code = 60303,cantonId=67,name="Potrero Grande"},
              new District{code = 60304,cantonId=67,name="Boruca"},
              new District{code = 60305,cantonId=67,name="Pilas"},
              new District{code = 60306,cantonId=67,name="Colinas o Bajo de Maíz"},
              new District{code = 60307,cantonId=67,name="Chánguena"},
              new District{code = 60308,cantonId=67,name="Bioley"},
              new District{code = 60309,cantonId=67,name="Brunka"},
              new District{code = 60401,cantonId=68,name="Miramar"},
              new District{code = 60402,cantonId=68,name="Unión"},
              new District{code = 60403,cantonId=68,name="San Isidro"},
              new District{code = 60501,cantonId=69,name="Puerto Cortés"},
              new District{code = 60502,cantonId=69,name="Palmar"},
              new District{code = 60503,cantonId=69,name="Sierpe"},
              new District{code = 60504,cantonId=69,name="Bahía Ballena"},
              new District{code = 60505,cantonId=69,name="Piedras Blancas"},
              new District{code = 60601,cantonId=70,name="Quepos"},
              new District{code = 60602,cantonId=70,name="Savegre"},
              new District{code = 60603,cantonId=70,name="Naranjito"},
              new District{code = 60701,cantonId=71,name="Golfito"},
              new District{code = 60702,cantonId=71,name="Puerto Jiménez"},
              new District{code = 60703,cantonId=71,name="Guaycará"},
              new District{code = 60704,cantonId=71,name="Pavon"},
              new District{code = 60801,cantonId=72,name="San Vito"},
              new District{code = 60802,cantonId=72,name="Sabalito"},
              new District{code = 60803,cantonId=72,name="Agua Buena"},
              new District{code = 60804,cantonId=72,name="Limoncito"},
              new District{code = 60805,cantonId=72,name="Pittier"},
              new District{code = 60901,cantonId=73,name="Parrita"},
              new District{code = 61001,cantonId=74,name="Corredor"},
              new District{code = 61002,cantonId=74,name="La Cuesta"},
              new District{code = 61003,cantonId=74,name="Paso Canoas"},
              new District{code = 61004,cantonId=74,name="Laurel"},
              new District{code = 61101,cantonId=75,name="Jacó"},
              new District{code = 61102,cantonId=75,name="Tárcoles"},
              new District{code = 70101,cantonId=76,name="Limón"},
              new District{code = 70102,cantonId=76,name="Valle La Estrella"},
              new District{code = 70103,cantonId=76,name="Río Blanco"},
              new District{code = 70104,cantonId=76,name="Matama"},
              new District{code = 70201,cantonId=77,name="Guápiles"},
              new District{code = 70202,cantonId=77,name="Jiménez"},
              new District{code = 70203,cantonId=77,name="Rita"},
              new District{code = 70204,cantonId=77,name="Roxana"},
              new District{code = 70205,cantonId=77,name="Cariari"},
              new District{code = 70206,cantonId=77,name="Colorado"},
              new District{code = 70301,cantonId=78,name="Siquirres"},
              new District{code = 70302,cantonId=78,name="Pacuarito"},
              new District{code = 70303,cantonId=78,name="Florida"},
              new District{code = 70304,cantonId=78,name="Germania"},
              new District{code = 70305,cantonId=78,name="Cairo"},
              new District{code = 70306,cantonId=78,name="Alegría"},
              new District{code = 70401,cantonId=79,name="Bratsi"},
              new District{code = 70402,cantonId=79,name="Sixaola"},
              new District{code = 70403,cantonId=79,name="Cahuita"},
              new District{code = 70404,cantonId=79,name="Telire"},
              new District{code = 70501,cantonId=80,name="Matina"},
              new District{code = 70502,cantonId=80,name="Batán"},
              new District{code = 70503,cantonId=80,name="Carrandí"},
              new District{code = 70601,cantonId=81,name="Guácimo"},
              new District{code = 70602,cantonId=81,name="Mercedes"},
              new District{code = 70603,cantonId=81,name="Pocora"},
              new District{code = 70604,cantonId=81,name="Río Jiménez"},
              new District{code = 70605,cantonId=81,name="Duacarí"}
            };
                context.Districts.AddRange(districts);
                context.SaveChanges();
            }
        }
    }
}
