// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eventManagementAPI.Data;

#nullable disable

namespace eventManagementAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240911025332_eventManagementDB")]
    partial class eventManagementDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eventManagementAPI.Models.Canton", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_cantons");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("canton_name");

                    b.Property<int>("provinceId")
                        .HasColumnType("int")
                        .HasColumnName("fk_provinces");

                    b.HasKey("id");

                    b.HasIndex("provinceId");

                    b.ToTable("Cantons", (string)null);
                });

            modelBuilder.Entity("eventManagementAPI.Models.District", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_districts");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cantonId")
                        .HasColumnType("int")
                        .HasColumnName("fk_cantons");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("district_name");

                    b.HasKey("id");

                    b.HasIndex("cantonId");

                    b.ToTable("Districts", (string)null);
                });

            modelBuilder.Entity("eventManagementAPI.Models.Event", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_events");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("cantonId")
                        .HasColumnType("int")
                        .HasColumnName("fk_cantons");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("event_description");

                    b.Property<string>("details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("event_details");

                    b.Property<int>("districtId")
                        .HasColumnType("int")
                        .HasColumnName("fk_districts");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<string>("exactPlace")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("exact_place");

                    b.Property<TimeSpan>("finishingTime")
                        .HasColumnType("time")
                        .HasColumnName("finishing_time");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("event_name");

                    b.Property<int>("provinceId")
                        .HasColumnType("int")
                        .HasColumnName("fk_provinces");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.Property<TimeSpan>("startingTime")
                        .HasColumnType("time")
                        .HasColumnName("starting_time");

                    b.HasKey("id");

                    b.HasIndex("cantonId");

                    b.HasIndex("districtId");

                    b.HasIndex("provinceId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("eventManagementAPI.Models.Province", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_provinces");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("province_name");

                    b.HasKey("id");

                    b.ToTable("Provinces", (string)null);
                });

            modelBuilder.Entity("eventManagementAPI.Models.Token", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_tokens");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("expiration")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiration");

                    b.Property<bool>("isRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked");

                    b.Property<string>("jwtToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jwt_token");

                    b.Property<int>("userId")
                        .HasColumnType("int")
                        .HasColumnName("fk_users");

                    b.HasKey("id");

                    b.HasIndex("UserId");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("eventManagementAPI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_users");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cellphone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cellphone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("userTypeId")
                        .HasColumnType("int")
                        .HasColumnName("fk_user_types");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("id");

                    b.HasIndex("userTypeId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            cellphone = "1-910-611-3821 x801",
                            email = "Emelie_Keeling@yahoo.com",
                            lastname = "Herman",
                            password = "$2a$11$eTwJG7xJHHwn4mea5LrfieOpB1x3FRTiLepIW/UJezvEx4dzi6bkK",
                            userTypeId = 1,
                            username = "Alexzander66"
                        },
                        new
                        {
                            id = 2,
                            cellphone = "(706) 616-2121 x772",
                            email = "Rebekah52@hotmail.com",
                            lastname = "Pfannerstill",
                            password = "$2a$11$6FJNjqUBHJb14yxN1aWee.k3DbIzGg00kz90h0ng.C3mrnW95dDT6",
                            userTypeId = 1,
                            username = "Kamryn.Daniel"
                        },
                        new
                        {
                            id = 3,
                            cellphone = "1-416-316-1051",
                            email = "Nicholaus.Tillman32@gmail.com",
                            lastname = "Beier",
                            password = "$2a$11$qqTvRyZLLC9Cj.TxuddRBe4kdfa38Uz7aRS/Ojf6AHymdQZ1AhaGq",
                            userTypeId = 2,
                            username = "Gloria.Koch85"
                        },
                        new
                        {
                            id = 4,
                            cellphone = "651.705.4009",
                            email = "Clementina70@gmail.com",
                            lastname = "Wunsch",
                            password = "$2a$11$yf1lyuwSzICFCUBxKFSFvuAxeJymH5U1rsQ5/FGzXOZjgr/cFdune",
                            userTypeId = 2,
                            username = "Daphne.Lang"
                        },
                        new
                        {
                            id = 5,
                            cellphone = "(340) 702-3695 x726",
                            email = "Alfreda.Schimmel@hotmail.com",
                            lastname = "Moen",
                            password = "$2a$11$hvpXX2VMzKzLatrqSh1svu4n/AhYv0vMa0SluUHT46vpxBBMNnC4O",
                            userTypeId = 2,
                            username = "Lorine_Hand97"
                        },
                        new
                        {
                            id = 6,
                            cellphone = "1-284-401-8648 x039",
                            email = "Gussie.Sauer70@hotmail.com",
                            lastname = "Morissette",
                            password = "$2a$11$W/Z1zMBor21xfRpq2zyIEOGOfhUXDyx.T4RFaY9XrqPkyWwstwAJ2",
                            userTypeId = 2,
                            username = "Mavis58"
                        },
                        new
                        {
                            id = 7,
                            cellphone = "1-308-741-0671 x992",
                            email = "Lia_Fahey@gmail.com",
                            lastname = "Greenfelder",
                            password = "$2a$11$gKirFDjKGQ2Ew1UgXGvNCOfkOL29Ss0BAIVhJwMhkNKFGkXcmK35C",
                            userTypeId = 1,
                            username = "Michel57"
                        },
                        new
                        {
                            id = 8,
                            cellphone = "445.304.1820 x05637",
                            email = "Marilou92@yahoo.com",
                            lastname = "Aufderhar",
                            password = "$2a$11$7wOAnsHYw8aJ65q8ypdDpum/dXUdCH4W74HsWOSd72nlByw4tRFo.",
                            userTypeId = 2,
                            username = "Enos.Gusikowski12"
                        },
                        new
                        {
                            id = 9,
                            cellphone = "657-859-2853 x16522",
                            email = "Kali_Corwin65@yahoo.com",
                            lastname = "Crooks",
                            password = "$2a$11$VzfKXnEZMgcerXZeEQCJmu9hGR.oUXwYFy34bSVldAgHPljI7yIlq",
                            userTypeId = 2,
                            username = "Jeremy.Cormier42"
                        },
                        new
                        {
                            id = 10,
                            cellphone = "(904) 636-7904 x9924",
                            email = "Elena_Wilderman24@hotmail.com",
                            lastname = "Reynolds",
                            password = "$2a$11$gtWvD0p8KLT/EUY0VZ5aO.8ndKlXRlHnNQbSl1fkP/qW.tUeyDAR6",
                            userTypeId = 2,
                            username = "Giovani42"
                        },
                        new
                        {
                            id = 11,
                            cellphone = "586.753.3963",
                            email = "Hailey.Nicolas@yahoo.com",
                            lastname = "Murray",
                            password = "$2a$11$LZRb.L93ArncwlZhTPNCN.H7DiSMfBZgmesEdYuAcBjyXFSzKOIHi",
                            userTypeId = 1,
                            username = "Eliane.Keeling"
                        },
                        new
                        {
                            id = 12,
                            cellphone = "(424) 923-7923 x19608",
                            email = "Angela3@gmail.com",
                            lastname = "White",
                            password = "$2a$11$eiuKPsamGKQODE9C004I7Ow4YYsYvXm0fy7jpN6BGxWoxYUDqJUqi",
                            userTypeId = 1,
                            username = "Janice19"
                        },
                        new
                        {
                            id = 13,
                            cellphone = "1-285-500-0561",
                            email = "Rhiannon.Mraz@gmail.com",
                            lastname = "Weimann",
                            password = "$2a$11$j5S5yB9AKkqq12GRCCq.J.fKSQKSY7Qaj78wXEqQfQgssxBt0KXHK",
                            userTypeId = 1,
                            username = "Lela18"
                        },
                        new
                        {
                            id = 14,
                            cellphone = "1-419-473-2352 x73721",
                            email = "Houston.Wunsch36@gmail.com",
                            lastname = "Ratke",
                            password = "$2a$11$LJRakr5Cg/kAF/NcciO2ee8bdcClR8Ly67NH45WlcrrHzLNyPvTpO",
                            userTypeId = 2,
                            username = "Agnes_Kirlin"
                        },
                        new
                        {
                            id = 15,
                            cellphone = "927-924-3630",
                            email = "Julia.Keeling@hotmail.com",
                            lastname = "Jacobs",
                            password = "$2a$11$K/H8yZCTacVpJCzGFrdPROC3Lz1k19q0VWIZEp0/kHEDU83RA68lW",
                            userTypeId = 1,
                            username = "Thomas.Windler"
                        },
                        new
                        {
                            id = 16,
                            cellphone = "(712) 298-5191",
                            email = "Alisha.Murphy@gmail.com",
                            lastname = "Macejkovic",
                            password = "$2a$11$jjaVzE5BPPXn0E2xTWrSo.zsZh2b6eVarT.dgMrOuNQb3N8FsQZnq",
                            userTypeId = 2,
                            username = "Tara.Pouros"
                        },
                        new
                        {
                            id = 17,
                            cellphone = "309.945.8753",
                            email = "Vicky.Wisoky48@yahoo.com",
                            lastname = "Purdy",
                            password = "$2a$11$eCG8miFlc2AAmjzDHqtDgexhg3FdRie1NxQYCbAzvJFc00dMg3BpS",
                            userTypeId = 2,
                            username = "Lavon64"
                        },
                        new
                        {
                            id = 18,
                            cellphone = "1-507-707-0018 x82874",
                            email = "Carlee79@hotmail.com",
                            lastname = "Homenick",
                            password = "$2a$11$LoT71b5dSkvyxUH.Cd07GeN.Fm9NeR35D5fB.66phiSZL4sLJBv2a",
                            userTypeId = 2,
                            username = "Jennings72"
                        },
                        new
                        {
                            id = 19,
                            cellphone = "800.791.0462",
                            email = "Virginie.Leannon39@yahoo.com",
                            lastname = "Armstrong",
                            password = "$2a$11$1Ht0GUAX23FOiwFQraGgVuoaUYrIzuAGSc/5t2LWCVxkhfCgulVQ6",
                            userTypeId = 2,
                            username = "Maye.Terry"
                        },
                        new
                        {
                            id = 20,
                            cellphone = "585.747.4871",
                            email = "Felipe_Zulauf@hotmail.com",
                            lastname = "Kulas",
                            password = "$2a$11$sBZ6upUkKfbxyXhuSBBkIOu4mwr2F5Z5QN5DVnJvQ5bUZlt28KFfW",
                            userTypeId = 1,
                            username = "Sven.Torp"
                        },
                        new
                        {
                            id = 21,
                            cellphone = "562.489.7316",
                            email = "Noemi25@hotmail.com",
                            lastname = "Wunsch",
                            password = "$2a$11$oTGEoSKW2ZZG5syf8u/RVOwNChXQK0utW1C5T/j2ZnYKeIel/XGpG",
                            userTypeId = 2,
                            username = "Jarod.Schulist"
                        },
                        new
                        {
                            id = 22,
                            cellphone = "920-378-8447 x2246",
                            email = "Lupe.Yost@gmail.com",
                            lastname = "Von",
                            password = "$2a$11$Mj2Eo/VOo2yloIHGUDw81uVneQEgyAcm6gIXO7UMSv3TdUNWtkinS",
                            userTypeId = 2,
                            username = "Craig57"
                        },
                        new
                        {
                            id = 23,
                            cellphone = "515-425-7223 x182",
                            email = "Melvina4@gmail.com",
                            lastname = "Connelly",
                            password = "$2a$11$9xl8kEB3.SO9Ix7c8jDv4OBpN2Xx6fxQqBToXYlqrpsBpc3v/euAG",
                            userTypeId = 1,
                            username = "Kaya.Satterfield89"
                        },
                        new
                        {
                            id = 24,
                            cellphone = "493.295.9244 x402",
                            email = "Magnus_Gutkowski@hotmail.com",
                            lastname = "Ondricka",
                            password = "$2a$11$IlxAE.9hCsDcGv9gR8nRz.yfGpofQ87E1VgbJLOFrLBV1pUQqolKm",
                            userTypeId = 1,
                            username = "Olen.Aufderhar"
                        },
                        new
                        {
                            id = 25,
                            cellphone = "1-994-758-7370 x1392",
                            email = "Green_Fay47@gmail.com",
                            lastname = "Conroy",
                            password = "$2a$11$ZXM7nuxFNdHgC4wv3OX2EO6/TpMLyaLRs2BQ6IeBfbrjkA7L5q/eO",
                            userTypeId = 1,
                            username = "Koby_Bailey"
                        },
                        new
                        {
                            id = 26,
                            cellphone = "(250) 489-2512 x716",
                            email = "Kaylee_Mayer71@gmail.com",
                            lastname = "Hermiston",
                            password = "$2a$11$fsLY0EjGyNoj2khqGjiyYePfnQTj4EusislI5trL3AMWaav5DClmu",
                            userTypeId = 1,
                            username = "Alva30"
                        },
                        new
                        {
                            id = 27,
                            cellphone = "(842) 798-2048",
                            email = "Ellsworth31@hotmail.com",
                            lastname = "Osinski",
                            password = "$2a$11$rzVuHTL/.a2KuXXVUGSq..MmgD4UAf9Q0HUZUcRRm6mNiB7/GXKcG",
                            userTypeId = 1,
                            username = "Zoey.Muller5"
                        },
                        new
                        {
                            id = 28,
                            cellphone = "659-468-1448 x3509",
                            email = "Patience.Bauch@yahoo.com",
                            lastname = "Schaefer",
                            password = "$2a$11$ZNGO4sZJ7LZKtAplq3L7/O/6dmmn0/FRFQvaa8Qt51X8eYZUzE4DC",
                            userTypeId = 1,
                            username = "Henri_Bauch"
                        },
                        new
                        {
                            id = 29,
                            cellphone = "955-502-6208 x879",
                            email = "Mittie.Breitenberg99@yahoo.com",
                            lastname = "Morar",
                            password = "$2a$11$tutrnPDqnRbJfsiyOBC0L.G6tP/BfUveiyOOwpa7ohHHMaruZMZj.",
                            userTypeId = 2,
                            username = "Vicente48"
                        },
                        new
                        {
                            id = 30,
                            cellphone = "(614) 405-6375",
                            email = "Edward41@yahoo.com",
                            lastname = "Deckow",
                            password = "$2a$11$FVLHMuYmmbyBSNiFsblasu2OcFyisI9D//aerzaTFmS1PBmmbNeH2",
                            userTypeId = 1,
                            username = "Lora_Rutherford4"
                        },
                        new
                        {
                            id = 31,
                            cellphone = "1-533-550-3287 x52583",
                            email = "Ashlynn.Collier22@hotmail.com",
                            lastname = "Schulist",
                            password = "$2a$11$cw.0mwGk/lj2Es9YSfsBTeW5QAtVlu2YKzoJ1FXFRt4RD6DXUJ/g6",
                            userTypeId = 1,
                            username = "Anne38"
                        },
                        new
                        {
                            id = 32,
                            cellphone = "736-391-2117",
                            email = "Chasity.Rempel13@gmail.com",
                            lastname = "Mayer",
                            password = "$2a$11$bTb/y1YF0tRe4eRQk/0b2eqmCWs4s7pL.aKJ8STrcKOZxsYu7sZCa",
                            userTypeId = 2,
                            username = "Titus_Kuhlman25"
                        },
                        new
                        {
                            id = 33,
                            cellphone = "994-466-9370 x9253",
                            email = "Tyson.Johnston@yahoo.com",
                            lastname = "Langworth",
                            password = "$2a$11$hxVPVLCsbTMafsrs2Q6eBO2an416JpvRo9XOqRKFJ2s2boY2egPE2",
                            userTypeId = 1,
                            username = "Evans14"
                        },
                        new
                        {
                            id = 34,
                            cellphone = "215.660.5589 x5368",
                            email = "Francis92@yahoo.com",
                            lastname = "Dach",
                            password = "$2a$11$vgwYhD9gTfBtQocTZ3NMWe8dYmLLqLJKPLZ75YSjzyjraUa5GviRa",
                            userTypeId = 1,
                            username = "Brayan.Considine99"
                        },
                        new
                        {
                            id = 35,
                            cellphone = "(787) 713-4450 x106",
                            email = "Lauryn83@gmail.com",
                            lastname = "Botsford",
                            password = "$2a$11$vXxXxG2PoK6TDlLrgt.NguV6S.FWwMtnfCve9vXU1L8rVs4d5CpVm",
                            userTypeId = 1,
                            username = "Clemmie_Grady41"
                        },
                        new
                        {
                            id = 36,
                            cellphone = "1-244-227-5107",
                            email = "Estevan_Brekke@yahoo.com",
                            lastname = "Hettinger",
                            password = "$2a$11$.n52YyPhQNrrcvLSEHEfxuEQn5jatedPHImPpG5kTQcC/vFYEkRkm",
                            userTypeId = 2,
                            username = "Valentin68"
                        },
                        new
                        {
                            id = 37,
                            cellphone = "(317) 725-4687 x0916",
                            email = "Krystel84@hotmail.com",
                            lastname = "Yundt",
                            password = "$2a$11$ifZaNPEVBTYAI9nhjZLIW.iJoPaUdMFFk6pn0BEwEzMP8IMAms.72",
                            userTypeId = 2,
                            username = "Howard_Von"
                        },
                        new
                        {
                            id = 38,
                            cellphone = "994-671-6129 x166",
                            email = "Linnie_Durgan14@yahoo.com",
                            lastname = "Funk",
                            password = "$2a$11$GuozC5fyC4Sy3ZH2eq4N9uskddJL0BPvi.LzO/AXemMh4aAtmlxBO",
                            userTypeId = 1,
                            username = "Grady_Boyer"
                        },
                        new
                        {
                            id = 39,
                            cellphone = "327.452.3992",
                            email = "Cleora25@gmail.com",
                            lastname = "Koss",
                            password = "$2a$11$kmckVAy6egoiupwORoML6.4kzB12ocylPcmV8huAsGuY7LeHLt2Fq",
                            userTypeId = 1,
                            username = "Adolph.Breitenberg"
                        },
                        new
                        {
                            id = 40,
                            cellphone = "1-549-434-0910 x5179",
                            email = "Marques47@gmail.com",
                            lastname = "Hudson",
                            password = "$2a$11$f870dPlsH833wgvCjZHYW.NoAopS/miX5OJGEoz9L3CzCNuMG2MQe",
                            userTypeId = 2,
                            username = "Warren5"
                        },
                        new
                        {
                            id = 41,
                            cellphone = "1-405-546-1199",
                            email = "Bartholome.Kuhlman@hotmail.com",
                            lastname = "Schuster",
                            password = "$2a$11$9o/n7X9gYHOyYt7gHA97DuUCjButNRRp7AxRdN.Ud4B0a4TMI8Q0S",
                            userTypeId = 1,
                            username = "Micaela_Klocko20"
                        },
                        new
                        {
                            id = 42,
                            cellphone = "(796) 684-6662",
                            email = "Alda.Kreiger@gmail.com",
                            lastname = "Satterfield",
                            password = "$2a$11$SQEvF0kWABSEuEkRSHtlZuhrp0RdA40NeWPkwJwHk.7ma.d69/YH2",
                            userTypeId = 2,
                            username = "Kaleb.Parisian"
                        },
                        new
                        {
                            id = 43,
                            cellphone = "(702) 757-8966",
                            email = "Priscilla.Balistreri@hotmail.com",
                            lastname = "Ruecker",
                            password = "$2a$11$Lu8AcmPFm5nPHh1iwTiQO.9WtY9XktDo8DvSNgZ.qS1Ir9TxMuFrW",
                            userTypeId = 1,
                            username = "Tierra7"
                        },
                        new
                        {
                            id = 44,
                            cellphone = "977-680-7737",
                            email = "Elaina_Beer@hotmail.com",
                            lastname = "Blanda",
                            password = "$2a$11$lY3xVkt/EH4kyVuXSCk7FOHdk.h381k4zO/IJPGwPOZ7PpVZ11D42",
                            userTypeId = 2,
                            username = "Preston_Rohan"
                        },
                        new
                        {
                            id = 45,
                            cellphone = "237-406-3979",
                            email = "Clair79@yahoo.com",
                            lastname = "Keebler",
                            password = "$2a$11$CWo6DcxbvxLsLO5Ldmk9M.TJLr0fyf1x2m5zJnpbrFOMvr3VqRugu",
                            userTypeId = 1,
                            username = "Alta_Nicolas"
                        },
                        new
                        {
                            id = 46,
                            cellphone = "(456) 633-0961",
                            email = "Verla.Bailey@yahoo.com",
                            lastname = "Lehner",
                            password = "$2a$11$M6/zhb8mTuwVwcmiVqg8U.bRZ51pmjsXcv3nTx/c6v4hTlPRLhU4C",
                            userTypeId = 1,
                            username = "Anika_Lockman"
                        },
                        new
                        {
                            id = 47,
                            cellphone = "1-510-348-5339 x72878",
                            email = "Shaniya25@gmail.com",
                            lastname = "Cruickshank",
                            password = "$2a$11$o.VR/G22pypGR4Y8t0mkrOfF6CpTFPaLvuSJ/pNQ92bR2VftaByFi",
                            userTypeId = 1,
                            username = "Clarissa_Powlowski"
                        },
                        new
                        {
                            id = 48,
                            cellphone = "696.234.5017",
                            email = "Santa_Grimes12@gmail.com",
                            lastname = "Greenfelder",
                            password = "$2a$11$Fi6Es/WFLmYe6LBsdL.5VO79Fh9x80ZEEwx/O3prW3WZ3FFJAc4YO",
                            userTypeId = 1,
                            username = "Thad_Zieme"
                        },
                        new
                        {
                            id = 49,
                            cellphone = "(567) 307-7893 x4292",
                            email = "Christina_Swaniawski73@yahoo.com",
                            lastname = "Reichel",
                            password = "$2a$11$.d.nm5rcTNnsfGxCj/th3uXRyU/Kbv5xlHzu1iMA/ajSX5sGac.Hy",
                            userTypeId = 2,
                            username = "Alena_Turner20"
                        },
                        new
                        {
                            id = 50,
                            cellphone = "519.956.1685 x0897",
                            email = "Berniece.Ankunding@gmail.com",
                            lastname = "Hilll",
                            password = "$2a$11$F/9i7PtCFYDfPrnht83yp.ECpZZu1K2a8ty1n6ErN1SEX89Xb2WuG",
                            userTypeId = 2,
                            username = "Kamille6"
                        });
                });

            modelBuilder.Entity("eventManagementAPI.Models.UserType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_user_types");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_type_description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_type_name");

                    b.HasKey("id");

                    b.ToTable("user_types", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "User with full administrative rights",
                            name = "Administrator"
                        },
                        new
                        {
                            id = 2,
                            description = "User with read-only access",
                            name = "Viewer"
                        });
                });

            modelBuilder.Entity("eventManagementAPI.Models.Canton", b =>
                {
                    b.HasOne("eventManagementAPI.Models.Province", "province")
                        .WithMany("cantons")
                        .HasForeignKey("provinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("province");
                });

            modelBuilder.Entity("eventManagementAPI.Models.District", b =>
                {
                    b.HasOne("eventManagementAPI.Models.Canton", "canton")
                        .WithMany("districts")
                        .HasForeignKey("cantonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("canton");
                });

            modelBuilder.Entity("eventManagementAPI.Models.Event", b =>
                {
                    b.HasOne("eventManagementAPI.Models.Canton", "canton")
                        .WithMany("events")
                        .HasForeignKey("cantonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eventManagementAPI.Models.District", "district")
                        .WithMany("events")
                        .HasForeignKey("districtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("eventManagementAPI.Models.Province", "province")
                        .WithMany("events")
                        .HasForeignKey("provinceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("canton");

                    b.Navigation("district");

                    b.Navigation("province");
                });

            modelBuilder.Entity("eventManagementAPI.Models.Token", b =>
                {
                    b.HasOne("eventManagementAPI.Models.User", "user")
                        .WithMany("Tokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("eventManagementAPI.Models.User", b =>
                {
                    b.HasOne("eventManagementAPI.Models.UserType", "userType")
                        .WithMany("users")
                        .HasForeignKey("userTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userType");
                });

            modelBuilder.Entity("eventManagementAPI.Models.Canton", b =>
                {
                    b.Navigation("districts");

                    b.Navigation("events");
                });

            modelBuilder.Entity("eventManagementAPI.Models.District", b =>
                {
                    b.Navigation("events");
                });

            modelBuilder.Entity("eventManagementAPI.Models.Province", b =>
                {
                    b.Navigation("cantons");

                    b.Navigation("events");
                });

            modelBuilder.Entity("eventManagementAPI.Models.User", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("eventManagementAPI.Models.UserType", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
