// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eventManagementAPI.Data;

#nullable disable

namespace eventManagementAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240910002504_eventManagementDB")]
    partial class eventManagementDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eventManagementAPI.Models.Token", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_tokens");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("expiration")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiration");

                    b.Property<bool>("isRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked");

                    b.Property<string>("jwtToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jwt_token");

                    b.Property<int>("userId")
                        .HasColumnType("int")
                        .HasColumnName("fk_users");

                    b.HasKey("id");

                    b.HasIndex("userId");

                    b.ToTable("tokens", (string)null);
                });

            modelBuilder.Entity("eventManagementAPI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_users");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cellphone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cellphone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("userTypeId")
                        .HasColumnType("int")
                        .HasColumnName("fk_user_types");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("id");

                    b.HasIndex("userTypeId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            cellphone = "562.264.2742 x544",
                            email = "Keira.Nicolas84@gmail.com",
                            lastname = "Legros",
                            password = "$2a$11$yNrfGQzhbVqeK6zQonrgl.tWvCFtikIMhqKI7y15aftS7bQX1/Q6G",
                            userTypeId = 1,
                            username = "Lucas36"
                        },
                        new
                        {
                            id = 2,
                            cellphone = "448-442-9521",
                            email = "Hailee.OConnell18@yahoo.com",
                            lastname = "Herzog",
                            password = "$2a$11$uzc5xMAdXdGyAKxnFk07u.T/E4V/gFIqeq8QwZF9CtC/cw338yrtW",
                            userTypeId = 1,
                            username = "Ethyl44"
                        },
                        new
                        {
                            id = 3,
                            cellphone = "450-357-4059 x030",
                            email = "Baron.Connelly0@gmail.com",
                            lastname = "Stanton",
                            password = "$2a$11$NI.vrK.U4qiVRIKYH0HaYOlMN1zFPWlB0vl4Hhf2vkukODhucyOv6",
                            userTypeId = 2,
                            username = "Allene8"
                        },
                        new
                        {
                            id = 4,
                            cellphone = "968-665-7658",
                            email = "Curtis.Reichel2@gmail.com",
                            lastname = "Botsford",
                            password = "$2a$11$a0V1rWi5lgUFa2/DfrPF6eb9fq8OLCsnx25TfR7Oq61iX52/C17ZW",
                            userTypeId = 1,
                            username = "Abby_Oberbrunner75"
                        },
                        new
                        {
                            id = 5,
                            cellphone = "378-357-8910 x055",
                            email = "Lesley_Rath14@gmail.com",
                            lastname = "Kulas",
                            password = "$2a$11$RKOHWrwpHeCvoqa18p2iBut0tbZ6vWIwzajhJOJ11ppCW2nb0jTHm",
                            userTypeId = 1,
                            username = "Clarabelle_Murray"
                        },
                        new
                        {
                            id = 6,
                            cellphone = "759.980.8957",
                            email = "Jadyn13@yahoo.com",
                            lastname = "Gleichner",
                            password = "$2a$11$y4Rschu8GHQyFf.T94Q9P.GZKXZmPRuYprd3hH0doYcmnpbp2o60e",
                            userTypeId = 2,
                            username = "Major_Hammes"
                        },
                        new
                        {
                            id = 7,
                            cellphone = "(942) 505-8234 x9374",
                            email = "Izaiah.Heidenreich@yahoo.com",
                            lastname = "Conn",
                            password = "$2a$11$wO.l3qjQpj1v5jtc3xkAbuR3YIi3uiTGhTdSc8YiqWGDyQ8K58106",
                            userTypeId = 1,
                            username = "Jessie80"
                        },
                        new
                        {
                            id = 8,
                            cellphone = "343.357.7542 x779",
                            email = "Therese61@hotmail.com",
                            lastname = "Monahan",
                            password = "$2a$11$S.KWeypuCqlJO5pUpCK2m.4wmX.3GOLUqPW8nAWlNQ4ruSY2yyv8q",
                            userTypeId = 1,
                            username = "Lavon_Schowalter32"
                        },
                        new
                        {
                            id = 9,
                            cellphone = "1-544-882-1230",
                            email = "Roberta.Schroeder80@hotmail.com",
                            lastname = "Skiles",
                            password = "$2a$11$AeDpcs279/vt3PFKjYtL0u.f1TnPfttfxZzRD/OyTlRFAl5Cbu77q",
                            userTypeId = 2,
                            username = "Marge.Hansen73"
                        },
                        new
                        {
                            id = 10,
                            cellphone = "418.296.9745",
                            email = "Guiseppe6@yahoo.com",
                            lastname = "Champlin",
                            password = "$2a$11$PbjHcUoh7/HZK/ZHkPfpweDmudarI.kFa6rPhXd/WEoqgqS9PGrH2",
                            userTypeId = 2,
                            username = "Janie.Howe34"
                        },
                        new
                        {
                            id = 11,
                            cellphone = "1-814-387-4321 x798",
                            email = "Marisol49@hotmail.com",
                            lastname = "Larson",
                            password = "$2a$11$4BtTkB..xAnXkHiitusgJuLGTs90XZI7YewQU3tR21DNDpJxXdVEC",
                            userTypeId = 1,
                            username = "Toy.Osinski"
                        },
                        new
                        {
                            id = 12,
                            cellphone = "863-866-9267 x66199",
                            email = "Mabel.Stoltenberg@hotmail.com",
                            lastname = "Wilderman",
                            password = "$2a$11$UVHxUcqXgsB0KBy7HH9VNeqYUN.M7/6VEXpUPPHa1AXNJKZTByB7i",
                            userTypeId = 2,
                            username = "Nellie.Kuhn"
                        },
                        new
                        {
                            id = 13,
                            cellphone = "(445) 360-4561 x8402",
                            email = "Benton.Hilpert68@hotmail.com",
                            lastname = "Feest",
                            password = "$2a$11$1Eq.OB0Ig/DKrRai8k2Apu/HPPw9KSDH7ERA4uTSqGP2EebRYNE/C",
                            userTypeId = 2,
                            username = "Vicenta_Trantow94"
                        },
                        new
                        {
                            id = 14,
                            cellphone = "779-337-8428 x781",
                            email = "Ona54@gmail.com",
                            lastname = "Mertz",
                            password = "$2a$11$Ou88NLFT5RBYmzl0ImrcxO818ep6iFix3JQiSknc3aYqh7FUHy64G",
                            userTypeId = 1,
                            username = "Shanna8"
                        },
                        new
                        {
                            id = 15,
                            cellphone = "1-254-905-5443 x81123",
                            email = "Al18@gmail.com",
                            lastname = "Ziemann",
                            password = "$2a$11$0bUsPJHO7TBMNzWy0PtD3uYiqr5B/FR3eh6yOnF6JB2DF7T3Q4PQC",
                            userTypeId = 1,
                            username = "Marian.Lindgren"
                        },
                        new
                        {
                            id = 16,
                            cellphone = "690-372-8123",
                            email = "Enola.Langosh40@hotmail.com",
                            lastname = "King",
                            password = "$2a$11$glCDryekWUP7qp5p/a2FEua/7PwcZJZVqInsDI15jg8b9ayDdjsQ6",
                            userTypeId = 1,
                            username = "Lempi_Price"
                        },
                        new
                        {
                            id = 17,
                            cellphone = "458.297.7981 x80095",
                            email = "Kennedi74@yahoo.com",
                            lastname = "Schuppe",
                            password = "$2a$11$5x.HrDlSl5Od9tjzl3DMLePLFszMXkIt0ekn4nYcQ61bo/mXvzsmq",
                            userTypeId = 2,
                            username = "Ozella51"
                        },
                        new
                        {
                            id = 18,
                            cellphone = "570-781-0290",
                            email = "Dylan_Wuckert8@hotmail.com",
                            lastname = "Parisian",
                            password = "$2a$11$v6AdgYriw3DM756E1/rPbOGHRT6e8twAnHnxd6aPZ5PwjvMfg/PaO",
                            userTypeId = 2,
                            username = "Tina51"
                        },
                        new
                        {
                            id = 19,
                            cellphone = "(489) 207-6122 x13188",
                            email = "Mikayla79@hotmail.com",
                            lastname = "Auer",
                            password = "$2a$11$DursMF74O6zN1uz1b8WDt.pGi.pgSCPMiEXCeKlpyXAPjG3UwSYgi",
                            userTypeId = 2,
                            username = "Celine80"
                        },
                        new
                        {
                            id = 20,
                            cellphone = "(849) 352-5296 x33093",
                            email = "Beth.Walker33@gmail.com",
                            lastname = "Cummerata",
                            password = "$2a$11$4m9koawdzhclrOM/ic4z6uZyOEmmzT73jS1gD/.cINOBaqGUrBBrO",
                            userTypeId = 2,
                            username = "Libby_Bernhard12"
                        },
                        new
                        {
                            id = 21,
                            cellphone = "1-867-460-4764",
                            email = "Citlalli.Cormier@hotmail.com",
                            lastname = "Breitenberg",
                            password = "$2a$11$fUMR7obktZ1OoYXW7.1/gOmKl1f35m4jWxPouGiDzXOhbxKcdqjuS",
                            userTypeId = 2,
                            username = "Gilberto7"
                        },
                        new
                        {
                            id = 22,
                            cellphone = "474-590-8290 x3442",
                            email = "Cordie9@yahoo.com",
                            lastname = "Bruen",
                            password = "$2a$11$AxHGum272pmmIKdiWdgBkeNgqy347mBbm5iciZfe651bvdEXSxBIe",
                            userTypeId = 2,
                            username = "Consuelo29"
                        },
                        new
                        {
                            id = 23,
                            cellphone = "426.508.0614 x102",
                            email = "Charles52@gmail.com",
                            lastname = "Lubowitz",
                            password = "$2a$11$eDAr6XScOLAUVjVCKhN8EeoCKhReDtKElQ7Zg1hjvEmw1/qL.1psW",
                            userTypeId = 1,
                            username = "Elda1"
                        },
                        new
                        {
                            id = 24,
                            cellphone = "837-972-4259 x76252",
                            email = "Rahul.Mraz@yahoo.com",
                            lastname = "Jacobson",
                            password = "$2a$11$5JNTcboI6A3VrqhZQwYjVuuPYfZntciJgkGQDBnfygRtPBCmPkU3S",
                            userTypeId = 1,
                            username = "Stanton.Dooley16"
                        },
                        new
                        {
                            id = 25,
                            cellphone = "738.508.8176 x4781",
                            email = "Reese_Schultz6@hotmail.com",
                            lastname = "Boyle",
                            password = "$2a$11$SEZP20KybWCUtMt6XqLO3OORAUcx0RlkMgTqDLwUSBPQMvNKx/csi",
                            userTypeId = 1,
                            username = "Wiley86"
                        },
                        new
                        {
                            id = 26,
                            cellphone = "1-538-467-4961",
                            email = "Elwyn.Sawayn72@gmail.com",
                            lastname = "Hyatt",
                            password = "$2a$11$nHHfQWsomS2JWcsN9W61JO.O8FkWBJyrggLolp8wNiXAmE1iVzhqS",
                            userTypeId = 1,
                            username = "Germaine_Mayer"
                        },
                        new
                        {
                            id = 27,
                            cellphone = "(688) 576-5530",
                            email = "Lawson70@hotmail.com",
                            lastname = "Wisozk",
                            password = "$2a$11$Ymd0eDKWCZHcArBJ.V6muesqsOYI5V7rOSOb4lc6gcgMIivHMne0y",
                            userTypeId = 2,
                            username = "Doyle.Rutherford"
                        },
                        new
                        {
                            id = 28,
                            cellphone = "778.590.7520 x710",
                            email = "Lexie.Feeney@yahoo.com",
                            lastname = "Renner",
                            password = "$2a$11$9sppO.oNNhqnSz5ojsoJp.3Cc5HKfCElAjI7Xq9QxKpBiRPCWU61G",
                            userTypeId = 1,
                            username = "Paolo56"
                        },
                        new
                        {
                            id = 29,
                            cellphone = "529-386-6617",
                            email = "Leslie_Quigley@yahoo.com",
                            lastname = "McLaughlin",
                            password = "$2a$11$ErMQcmdthKU692ZkXKuYo.F8umUDwuQ.hhm3BvXJnTrntN0xLAIJC",
                            userTypeId = 2,
                            username = "Alessia81"
                        },
                        new
                        {
                            id = 30,
                            cellphone = "1-771-938-9146",
                            email = "Fanny_Daniel17@yahoo.com",
                            lastname = "Ernser",
                            password = "$2a$11$NoijU92UrgkdW1po7C7NP.9OPZ4Nv.nhccdcBVYWk8F5DQIBcSaqe",
                            userTypeId = 2,
                            username = "Frederic_Connelly74"
                        },
                        new
                        {
                            id = 31,
                            cellphone = "892.414.4094 x058",
                            email = "Ron58@yahoo.com",
                            lastname = "Borer",
                            password = "$2a$11$kwmD3VJ3oR/ZuwyjkZr/HeBdZceHxrv4APJILb64JZPfV8VeEW7Xa",
                            userTypeId = 1,
                            username = "Kade_Lehner"
                        },
                        new
                        {
                            id = 32,
                            cellphone = "701.618.8356 x3380",
                            email = "Kayli.White@gmail.com",
                            lastname = "Schinner",
                            password = "$2a$11$RFE7eQc0RzTYtm/eBD2OA.5mGaBKzfrBCu4HY7Hwghc4zBcJCkOIO",
                            userTypeId = 1,
                            username = "Jesse_Purdy"
                        },
                        new
                        {
                            id = 33,
                            cellphone = "628.947.2594 x970",
                            email = "Aurelio.Braun16@yahoo.com",
                            lastname = "Heller",
                            password = "$2a$11$nw3WyU3UjurZ7ujNVqLEmuuyBHduhY2CNvZG.OjnziQXH80dmUkbC",
                            userTypeId = 2,
                            username = "Kaylin_Lakin"
                        },
                        new
                        {
                            id = 34,
                            cellphone = "1-356-988-1828",
                            email = "Rollin_Cummings69@gmail.com",
                            lastname = "Tremblay",
                            password = "$2a$11$H7XkK/lcITerudiiMji8veEZ08MBXwg2/gmJs0WwmNCZX8fDxejnO",
                            userTypeId = 2,
                            username = "Tamara_Lindgren"
                        },
                        new
                        {
                            id = 35,
                            cellphone = "738-637-3062",
                            email = "Peggie20@gmail.com",
                            lastname = "Konopelski",
                            password = "$2a$11$cL/RWbWb9QcZcweFsRJ4cOPRPAajCtsI1FV6X/SR6FkMVsBK49AoG",
                            userTypeId = 2,
                            username = "Aurelia.Wehner89"
                        },
                        new
                        {
                            id = 36,
                            cellphone = "1-939-409-7572 x8211",
                            email = "Zane78@hotmail.com",
                            lastname = "Dickinson",
                            password = "$2a$11$0pZTQ2uRSudfMqZknz31XO/YVZR3zi9C7pFRxczAO3zR5FJGUn5xm",
                            userTypeId = 2,
                            username = "Aric95"
                        },
                        new
                        {
                            id = 37,
                            cellphone = "711-459-1259 x850",
                            email = "Dorothy71@gmail.com",
                            lastname = "Hilpert",
                            password = "$2a$11$dvV3XNxY7frcTBd7WNlcq.xwyJ8monwhdkXc6M23pb74iocu2rKiy",
                            userTypeId = 2,
                            username = "Hillary87"
                        },
                        new
                        {
                            id = 38,
                            cellphone = "282.911.3114 x183",
                            email = "Melyna_Kuvalis@hotmail.com",
                            lastname = "Fadel",
                            password = "$2a$11$ctAFsweSQJnR58BQZdNrYeZ8Z7ZuQZ9j7xkJwUiSyS27oFf9BLBUS",
                            userTypeId = 1,
                            username = "Doris_Halvorson"
                        },
                        new
                        {
                            id = 39,
                            cellphone = "519.747.4805 x47266",
                            email = "Yvette_Schneider2@yahoo.com",
                            lastname = "Lemke",
                            password = "$2a$11$R1S0HAB5tly4f4RW5CnpBuiHa1Peibfk3iDWeoOBC0X7M7hvlbM7q",
                            userTypeId = 2,
                            username = "Zackary90"
                        },
                        new
                        {
                            id = 40,
                            cellphone = "(954) 652-4950 x570",
                            email = "Loyce.VonRueden81@hotmail.com",
                            lastname = "Koch",
                            password = "$2a$11$moyTsqhkQU3sANLSCkQlhufTrDsqSMXultSSEkxYV7pf3TgdX7tny",
                            userTypeId = 2,
                            username = "Kristian_Dietrich51"
                        },
                        new
                        {
                            id = 41,
                            cellphone = "317-864-9733",
                            email = "Gordon26@hotmail.com",
                            lastname = "Ryan",
                            password = "$2a$11$7Aj.KNvUS8PUc9xdzblam.NU1oIAKe5n.ZxTLeId76BDFAVtgmCxG",
                            userTypeId = 2,
                            username = "Phyllis.Cormier"
                        },
                        new
                        {
                            id = 42,
                            cellphone = "(430) 833-1364 x0240",
                            email = "Juliana_Casper32@gmail.com",
                            lastname = "Smitham",
                            password = "$2a$11$EqdOtXA1nuWakZBglKFMxOolpZAYlq7B9B48NknO30asPB2r1PpDy",
                            userTypeId = 2,
                            username = "Burnice12"
                        },
                        new
                        {
                            id = 43,
                            cellphone = "1-498-976-8188",
                            email = "Zander46@hotmail.com",
                            lastname = "Jast",
                            password = "$2a$11$qshdz8gpqP7E/VOHD0WFR.pBvy95DyG.yoa4/Y5I0tXipanQ9xlmi",
                            userTypeId = 2,
                            username = "Lori.Bahringer33"
                        },
                        new
                        {
                            id = 44,
                            cellphone = "432-629-9908 x4290",
                            email = "Sabryna30@gmail.com",
                            lastname = "Powlowski",
                            password = "$2a$11$Fr3mIZOe5ZnOAiS2BaWphOed/xzZdSe4NS8CrXwDKK38Sqk9TnXG6",
                            userTypeId = 2,
                            username = "Maxine.Jenkins"
                        },
                        new
                        {
                            id = 45,
                            cellphone = "1-266-565-6194 x29250",
                            email = "Joyce_Feest11@yahoo.com",
                            lastname = "Bartoletti",
                            password = "$2a$11$RCovUEr4Pn6AnIGhfmb2KOVUUoDDWaKOoOU6LFBMyOSt1pC9koo6O",
                            userTypeId = 1,
                            username = "Norene18"
                        },
                        new
                        {
                            id = 46,
                            cellphone = "551-608-9905 x4136",
                            email = "Webster.Haley@yahoo.com",
                            lastname = "Bashirian",
                            password = "$2a$11$qknjSF7DRpOdbFE30GaqPeOp.PoeYAr9E3ewLBFSf07.0GBLlLWBS",
                            userTypeId = 1,
                            username = "Alia.Stehr"
                        },
                        new
                        {
                            id = 47,
                            cellphone = "768-948-9352",
                            email = "Nels.Jenkins@gmail.com",
                            lastname = "Kub",
                            password = "$2a$11$crdNA264wfdSvYWqwhFxruka4TA1B.5QF9bUJBfXILgpfhzaVlBdS",
                            userTypeId = 1,
                            username = "Lue.Lowe"
                        },
                        new
                        {
                            id = 48,
                            cellphone = "1-363-486-4712",
                            email = "Isabell.Hermiston67@gmail.com",
                            lastname = "Koch",
                            password = "$2a$11$TdgUIPtZdOcjuoSFuqt.beMl.lilc7TmilQNkwrTM16w.htskfise",
                            userTypeId = 2,
                            username = "Beryl.Lemke99"
                        },
                        new
                        {
                            id = 49,
                            cellphone = "1-865-447-6597",
                            email = "Ellis_Mayert@gmail.com",
                            lastname = "Larson",
                            password = "$2a$11$/IC7Oqb8b2.VqTkKMlvLzOnsMqfQR3JQjZUrfIBuI8LNbQPiDxLDy",
                            userTypeId = 1,
                            username = "Vida_Rosenbaum"
                        },
                        new
                        {
                            id = 50,
                            cellphone = "1-489-557-0122 x722",
                            email = "Luciano21@yahoo.com",
                            lastname = "Monahan",
                            password = "$2a$11$USjY5jzsHlq/xZdCNT8.pOackLbRFX1p5cjuuvxblXTdZmoCfUeJO",
                            userTypeId = 1,
                            username = "Nannie40"
                        });
                });

            modelBuilder.Entity("eventManagementAPI.Models.UserType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_user_types");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_type_description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_type_name");

                    b.HasKey("id");

                    b.ToTable("user_types", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "User with full administrative rights",
                            name = "Administrator"
                        },
                        new
                        {
                            id = 2,
                            description = "User with read-only access",
                            name = "Viewer"
                        });
                });

            modelBuilder.Entity("eventManagementAPI.Models.Token", b =>
                {
                    b.HasOne("eventManagementAPI.Models.User", "user")
                        .WithMany("Tokens")
                        .HasForeignKey("userId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("eventManagementAPI.Models.User", b =>
                {
                    b.HasOne("eventManagementAPI.Models.UserType", "userType")
                        .WithMany("users")
                        .HasForeignKey("userTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userType");
                });

            modelBuilder.Entity("eventManagementAPI.Models.User", b =>
                {
                    b.Navigation("Tokens");
                });

            modelBuilder.Entity("eventManagementAPI.Models.UserType", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
