// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eventManagementAPI.Data;

#nullable disable

namespace eventManagementAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("eventManagementAPI.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pk_users");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("cellphone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("cellphone");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("lastname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("lastname");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password");

                    b.Property<int>("userTypeId")
                        .HasColumnType("int")
                        .HasColumnName("fk_user_types");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("id");

                    b.HasIndex("userTypeId");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            cellphone = "1-522-256-9487 x1121",
                            email = "Filiberto_Wolff@hotmail.com",
                            lastname = "McClure",
                            password = "$2a$11$msISkdlgDRy3D1UM3vsFLuovy6m/izvshqa54PLfSKlDyUMFQD6sa",
                            userTypeId = 1,
                            username = "Delilah_Russel"
                        },
                        new
                        {
                            id = 2,
                            cellphone = "823.410.9767 x6457",
                            email = "Randy_Yost9@gmail.com",
                            lastname = "Littel",
                            password = "$2a$11$z6BBEG7UTd3jpx9w4gG/uOaqroys8fWKaxol7EkdN8qEEN6bPv3wW",
                            userTypeId = 1,
                            username = "Luciano4"
                        },
                        new
                        {
                            id = 3,
                            cellphone = "464.689.0674",
                            email = "Ole_Mayert25@gmail.com",
                            lastname = "Erdman",
                            password = "$2a$11$DdEA/KvC8NmYYnYHA9OEQuHgUL3eGKGL0tzPGDofW4W.KVpVxGBR.",
                            userTypeId = 1,
                            username = "Dalton.Fritsch2"
                        },
                        new
                        {
                            id = 4,
                            cellphone = "505.238.8112",
                            email = "Herta_Becker79@gmail.com",
                            lastname = "Wuckert",
                            password = "$2a$11$YTMoHwXJ/Spf2Q/6acmWFuXRuf/BJN0hEM4hSytCqETkNwr.qX/PS",
                            userTypeId = 1,
                            username = "Loraine_Spinka"
                        },
                        new
                        {
                            id = 5,
                            cellphone = "710-486-6657 x9755",
                            email = "Kadin_Satterfield61@yahoo.com",
                            lastname = "Bahringer",
                            password = "$2a$11$3ZFc/BLILJn4qOpCLWqqZeGDT.nipbXoSuxvOiHceYjoNuQyrVrIK",
                            userTypeId = 2,
                            username = "Jordy28"
                        },
                        new
                        {
                            id = 6,
                            cellphone = "555.940.8213",
                            email = "Clara_Olson40@yahoo.com",
                            lastname = "Pollich",
                            password = "$2a$11$nKzY5BBKPg85Z9aTe.REg.WYCT1r2HzzDms9bb9kcRgGOU3dXmf6a",
                            userTypeId = 2,
                            username = "Pasquale.Ernser"
                        },
                        new
                        {
                            id = 7,
                            cellphone = "1-523-744-7418",
                            email = "Jarvis77@hotmail.com",
                            lastname = "Sauer",
                            password = "$2a$11$oUpZvNJ2equBaNj5dCBGPOQK92jlAGTDY13YjJlyLhdHS22es4Kj.",
                            userTypeId = 2,
                            username = "Jalon39"
                        },
                        new
                        {
                            id = 8,
                            cellphone = "1-720-600-7301 x067",
                            email = "Ali96@hotmail.com",
                            lastname = "Ledner",
                            password = "$2a$11$Uey9Gl9zv2/H4lpq2zPfi.X2MxP9mICYFcQxGWwIqhmy9T89a0rn.",
                            userTypeId = 1,
                            username = "Lisandro.Metz"
                        },
                        new
                        {
                            id = 9,
                            cellphone = "463-513-3990",
                            email = "Yessenia50@yahoo.com",
                            lastname = "Rempel",
                            password = "$2a$11$AX95PBYLTwu7mJ.UTOqBSuNT67QiQZ/yyn7gWtkSILG0c8gSNkoES",
                            userTypeId = 2,
                            username = "Earnest26"
                        },
                        new
                        {
                            id = 10,
                            cellphone = "1-513-725-3492 x74871",
                            email = "Carlie.Hackett@hotmail.com",
                            lastname = "Fay",
                            password = "$2a$11$lUw1x82aYM.hd7dEu0Xnwua8oLThQ9o1uQzqOlWZuHLCFWqbKHp5.",
                            userTypeId = 1,
                            username = "Tracy_Douglas"
                        },
                        new
                        {
                            id = 11,
                            cellphone = "1-726-979-3560 x07213",
                            email = "Mellie_Fadel@yahoo.com",
                            lastname = "Shields",
                            password = "$2a$11$Xw9q4gR.npIusYB2sbxUOOlPUcCaWmkhYOjo3uACWEX0r33jzcOKy",
                            userTypeId = 2,
                            username = "Lance.Marks"
                        },
                        new
                        {
                            id = 12,
                            cellphone = "521.480.5617 x412",
                            email = "America26@gmail.com",
                            lastname = "Ondricka",
                            password = "$2a$11$xQQWoM.6t7b6YDhGOCajg.CMNX6IUcS.Stxd5bVxkW/OG34oxCQEO",
                            userTypeId = 1,
                            username = "Winifred47"
                        },
                        new
                        {
                            id = 13,
                            cellphone = "694.519.1085",
                            email = "Andre_Schultz@yahoo.com",
                            lastname = "Wolf",
                            password = "$2a$11$ejpbqqlw.Ow5B7ljYZZR1u0vu5XSOOuCgI32M9DXt9GEofHXtLyvK",
                            userTypeId = 1,
                            username = "Maximillia26"
                        },
                        new
                        {
                            id = 14,
                            cellphone = "422.329.7588 x5792",
                            email = "Marcella28@gmail.com",
                            lastname = "Hayes",
                            password = "$2a$11$a8Rryh9u.PXPgyaqbnBEXeznpp0XgTIlxY6p22MFrcYIUMhUAt5V6",
                            userTypeId = 2,
                            username = "Osborne0"
                        },
                        new
                        {
                            id = 15,
                            cellphone = "211-846-5452",
                            email = "Roslyn45@gmail.com",
                            lastname = "Weissnat",
                            password = "$2a$11$TV8BIwrD65mGJpJqVYuwy.68JwF6t11qxZJOZoA0h5tsvnXYzMZo.",
                            userTypeId = 1,
                            username = "Stephanie_Erdman"
                        },
                        new
                        {
                            id = 16,
                            cellphone = "(270) 871-9190",
                            email = "Reina.Kohler@yahoo.com",
                            lastname = "Predovic",
                            password = "$2a$11$PtP85s6N7QdTyilGul5zB.Cg5DuxrjqoA5JC8XWpB13JoILQkk/6q",
                            userTypeId = 1,
                            username = "Julius_Von"
                        },
                        new
                        {
                            id = 17,
                            cellphone = "851.998.0873",
                            email = "Sadye60@yahoo.com",
                            lastname = "Nader",
                            password = "$2a$11$Akmx5vjZ5C.ftb.8yDvnDOODgmbKuLj/rglJZRu5sh9az4iH2i1BG",
                            userTypeId = 2,
                            username = "Lurline95"
                        },
                        new
                        {
                            id = 18,
                            cellphone = "1-857-495-4855 x7141",
                            email = "Orrin_Hoeger70@hotmail.com",
                            lastname = "Rowe",
                            password = "$2a$11$biythLrujxYXEpxHK3UY5uZ7q2jrxFS7pw2Ajnc75WmxQUXcYEPKa",
                            userTypeId = 2,
                            username = "Bernadette85"
                        },
                        new
                        {
                            id = 19,
                            cellphone = "(525) 914-4598 x856",
                            email = "Georgiana.Zieme@gmail.com",
                            lastname = "Fadel",
                            password = "$2a$11$KPbKdmQ4dnoV5X1.09h/I.Wk3Zczy.HaI7IJAVwi5k5XHgnKJc/mm",
                            userTypeId = 1,
                            username = "Amara87"
                        },
                        new
                        {
                            id = 20,
                            cellphone = "1-528-896-1224 x6684",
                            email = "Ruben_Metz@yahoo.com",
                            lastname = "Lakin",
                            password = "$2a$11$v3EVVAEu01mLAnACqphAP.9DZe6OVU.h5eCH6kCFo2ldePOpI3KkG",
                            userTypeId = 1,
                            username = "Bertrand.OReilly99"
                        },
                        new
                        {
                            id = 21,
                            cellphone = "(467) 241-9390",
                            email = "Myra.Wintheiser@gmail.com",
                            lastname = "Schmitt",
                            password = "$2a$11$.pm7pBdYIYZh4pg1nTqnNuHS9IdhBSRZVYS9WNMwKMfECxt4fBiWG",
                            userTypeId = 1,
                            username = "Nola_Hudson74"
                        },
                        new
                        {
                            id = 22,
                            cellphone = "(240) 689-7845",
                            email = "Lolita_Predovic28@hotmail.com",
                            lastname = "Wolff",
                            password = "$2a$11$lTcEwSTkBUREIa0.4XTTT.MJusf.dj/WT.e06f0mtjPRIjPyGtA7i",
                            userTypeId = 1,
                            username = "Keshaun.Terry"
                        },
                        new
                        {
                            id = 23,
                            cellphone = "606.706.1016 x268",
                            email = "Megane77@hotmail.com",
                            lastname = "Lindgren",
                            password = "$2a$11$qxDKCE02BnauRYrr0pyTJeYAzEOnKmClKLXAYX4WfkhiCSMh8A.cy",
                            userTypeId = 2,
                            username = "Lilian.Donnelly77"
                        },
                        new
                        {
                            id = 24,
                            cellphone = "624-718-6680",
                            email = "Alec62@hotmail.com",
                            lastname = "Bartoletti",
                            password = "$2a$11$kg1J0gZcxhvO4tDdXc5ZluBOXR7iGR8SyLO47TxytD7cYiaxYYPju",
                            userTypeId = 2,
                            username = "Abel.Durgan"
                        },
                        new
                        {
                            id = 25,
                            cellphone = "290.787.4537",
                            email = "Dameon_Block@hotmail.com",
                            lastname = "Bernier",
                            password = "$2a$11$XDXOcIXp0hJRz3vL1OCQSuDVuvmT7xVi83dh02SwGS10U2v0utpYq",
                            userTypeId = 2,
                            username = "Meda.Johnston39"
                        },
                        new
                        {
                            id = 26,
                            cellphone = "(414) 257-4080",
                            email = "Jamir.Hegmann@hotmail.com",
                            lastname = "Erdman",
                            password = "$2a$11$/wpYCl61BVVEWfIekffKq.FigXM9DCvsXZqrq9CtAXuy6xditCvZO",
                            userTypeId = 2,
                            username = "Twila.Turner88"
                        },
                        new
                        {
                            id = 27,
                            cellphone = "(379) 937-2042",
                            email = "Ozella.OConnell10@hotmail.com",
                            lastname = "Rice",
                            password = "$2a$11$zILoyPTepUJIvRDh/0ofT.UGfEo.HRsQisDdTXwlcEJRvsRMaUqVi",
                            userTypeId = 2,
                            username = "Julio.Simonis"
                        },
                        new
                        {
                            id = 28,
                            cellphone = "(883) 791-6852 x74047",
                            email = "Jermey.Botsford@hotmail.com",
                            lastname = "Olson",
                            password = "$2a$11$CmHmPTsiQOHkMG11o3iPqOA6Hmwly2zPlF.g6sQ4zyEdNCN/f6vyy",
                            userTypeId = 1,
                            username = "Zelma_Bashirian20"
                        },
                        new
                        {
                            id = 29,
                            cellphone = "614-713-3601 x6086",
                            email = "Mya.Franecki@hotmail.com",
                            lastname = "Kuhlman",
                            password = "$2a$11$bkYbAlpm9f3eL79TzzTUxenNUX8qMp7vLtUx1WYFh6D26.A8TC0qG",
                            userTypeId = 2,
                            username = "Wellington_King"
                        },
                        new
                        {
                            id = 30,
                            cellphone = "858.215.2932",
                            email = "Brannon.Abernathy@gmail.com",
                            lastname = "Nader",
                            password = "$2a$11$m6qMiFHCUOzZ6K3DmQIoh.rWK6Xdy2Yxd2RyfgbMImxuHpAC0lL4G",
                            userTypeId = 2,
                            username = "Ludwig_Crona"
                        },
                        new
                        {
                            id = 31,
                            cellphone = "(917) 824-2155",
                            email = "Zack_Rippin9@gmail.com",
                            lastname = "Labadie",
                            password = "$2a$11$CxkV23V0pj.ylz/xH7PliOeOW4yL1YvP4hcyIzegajseeu.lpmdsG",
                            userTypeId = 1,
                            username = "Nelson.Harvey"
                        },
                        new
                        {
                            id = 32,
                            cellphone = "341.500.6652",
                            email = "Alta.Heidenreich70@yahoo.com",
                            lastname = "Okuneva",
                            password = "$2a$11$hA4xZkOFfhlVIwVrrRZcrOXlMsbe6FnU.CpmgZw8e27lA3qll5Cf6",
                            userTypeId = 2,
                            username = "Lizeth_Miller"
                        },
                        new
                        {
                            id = 33,
                            cellphone = "1-704-408-3507 x9669",
                            email = "Tremaine.Denesik@yahoo.com",
                            lastname = "Kunze",
                            password = "$2a$11$/wE1eZ1JO9l9FBdwaCC/LOJxY002meNbWJJAYR3I4MIABSn5M5E02",
                            userTypeId = 1,
                            username = "Josie_Rempel84"
                        },
                        new
                        {
                            id = 34,
                            cellphone = "249-706-8458 x37413",
                            email = "Maxime35@gmail.com",
                            lastname = "Metz",
                            password = "$2a$11$D3o5K9ik8nzf6.UPBIgdlOUsiwpUjrQE.Z.xXt51PGii6pTPbEVUS",
                            userTypeId = 2,
                            username = "Lukas.Braun0"
                        },
                        new
                        {
                            id = 35,
                            cellphone = "1-242-892-0326 x3762",
                            email = "Boyd43@gmail.com",
                            lastname = "Koelpin",
                            password = "$2a$11$MQAiX5exFVdwKTurmHdGP.lOYxXBChzYaCf77mMBxcQFKwZ8GvKuy",
                            userTypeId = 2,
                            username = "Rhea.Zieme"
                        },
                        new
                        {
                            id = 36,
                            cellphone = "(870) 414-8033 x77104",
                            email = "Antonietta67@yahoo.com",
                            lastname = "Marks",
                            password = "$2a$11$B1MeOQ55785PBTl7PkbvledN4FQOnXkVOY/RUze6VRDJYtg1P47Wu",
                            userTypeId = 1,
                            username = "Hosea.Legros"
                        },
                        new
                        {
                            id = 37,
                            cellphone = "844-393-7770",
                            email = "Genesis_Koepp38@hotmail.com",
                            lastname = "Johnson",
                            password = "$2a$11$uYZlqGoCTZIdztzR6xlkFOs1sj8D2Kgchsc7mKWFOeqmboMr3m3oa",
                            userTypeId = 2,
                            username = "Katrina_Emard5"
                        },
                        new
                        {
                            id = 38,
                            cellphone = "1-302-487-0810",
                            email = "Linnie69@yahoo.com",
                            lastname = "Labadie",
                            password = "$2a$11$K147BSi2q0.a/RFl7t03ReMTOHoCTFeDZDOoit9zUBUQbE44aywE2",
                            userTypeId = 1,
                            username = "Yasmin66"
                        },
                        new
                        {
                            id = 39,
                            cellphone = "759.304.8182",
                            email = "Skye.Kreiger@gmail.com",
                            lastname = "Hansen",
                            password = "$2a$11$h7SaBMvyRXh8eJEdDfOwS.L8iUB3ZQCZzEpc.Nq.g/kWGEMLAh3Ya",
                            userTypeId = 1,
                            username = "Laurine88"
                        },
                        new
                        {
                            id = 40,
                            cellphone = "275-458-2494 x47206",
                            email = "Anastacio53@hotmail.com",
                            lastname = "Welch",
                            password = "$2a$11$ZGWFPh1fi/rtG0cxPikXruUkWPmO5n1vGuAcq8TX/puHzvElxINnO",
                            userTypeId = 2,
                            username = "Austyn_Kreiger"
                        },
                        new
                        {
                            id = 41,
                            cellphone = "(618) 344-0368 x78461",
                            email = "Elvis.Schmidt@gmail.com",
                            lastname = "Corwin",
                            password = "$2a$11$frc8XS8aYq.U4pyKSQ5GdeHPFaPDW7SX/Ug4YbzPQE7kbBKynCoXq",
                            userTypeId = 1,
                            username = "Antonietta.Upton17"
                        },
                        new
                        {
                            id = 42,
                            cellphone = "300-792-1164",
                            email = "Anderson73@yahoo.com",
                            lastname = "Treutel",
                            password = "$2a$11$ZOAz0sEgJqTEt0vYgM/Q0eZ6k.gQ6bxgMbKLwrVD73DuOlcBWY46q",
                            userTypeId = 2,
                            username = "Rosalee41"
                        },
                        new
                        {
                            id = 43,
                            cellphone = "1-442-792-0314",
                            email = "Lindsey.Nitzsche17@gmail.com",
                            lastname = "Fadel",
                            password = "$2a$11$jilRusorcd8YhjQIel5Bsuazp4wrjI2P67ODzHSDKS9c45TNjmvrm",
                            userTypeId = 1,
                            username = "Anya35"
                        },
                        new
                        {
                            id = 44,
                            cellphone = "573.584.9085",
                            email = "Kelton21@yahoo.com",
                            lastname = "Stanton",
                            password = "$2a$11$j/mXooKj/ueAfJMxZ4i96uw0BglMzESWBksA0UCd.9o3mOLsrf6.K",
                            userTypeId = 1,
                            username = "Melody82"
                        },
                        new
                        {
                            id = 45,
                            cellphone = "675.296.0682 x188",
                            email = "Stacy88@hotmail.com",
                            lastname = "Boyle",
                            password = "$2a$11$vDIJuyRYJr5H1Hg5bg7zeOgaaaoUidvpJzhkeSL.3jog5lGPa7Hma",
                            userTypeId = 2,
                            username = "Magdalena.Crist60"
                        },
                        new
                        {
                            id = 46,
                            cellphone = "1-381-321-8641",
                            email = "Ezekiel_Koss45@yahoo.com",
                            lastname = "Prosacco",
                            password = "$2a$11$rXXGMGh33ofZ7gd9Bd3P/OS5ce6KsD/ReTqq5kvkhfNWGLIBFSUg.",
                            userTypeId = 2,
                            username = "Emile.Gulgowski32"
                        },
                        new
                        {
                            id = 47,
                            cellphone = "770.362.1749",
                            email = "Clay.Goyette25@gmail.com",
                            lastname = "Skiles",
                            password = "$2a$11$kixwkjzd3mQSJV0ymHpoS.4Vy4Boy9vOg/RbEuDC6JOGC3YsTdtbq",
                            userTypeId = 1,
                            username = "Emily.Fay"
                        },
                        new
                        {
                            id = 48,
                            cellphone = "1-240-637-0034",
                            email = "Erich.Farrell@yahoo.com",
                            lastname = "Walker",
                            password = "$2a$11$LCSEYeU25pHZmcWffq55EOx3GWZp2CtfUzvTP3KcAcO/FMfm9yqVa",
                            userTypeId = 2,
                            username = "Glenda.Crona"
                        },
                        new
                        {
                            id = 49,
                            cellphone = "652-904-2947 x0754",
                            email = "Henry7@yahoo.com",
                            lastname = "Pouros",
                            password = "$2a$11$P5WksmfWa3q4GoLBcKMpYe1a/PxsJDM3sff2Ci1BgGrhN60ZBwDCK",
                            userTypeId = 2,
                            username = "Kayli42"
                        },
                        new
                        {
                            id = 50,
                            cellphone = "981-795-1145",
                            email = "Martina_Schiller0@yahoo.com",
                            lastname = "Abernathy",
                            password = "$2a$11$l9odNoWaJvPX2RqNUGucWeytzvCozMbwUFg5xfPL6w7TEB7aXxfxm",
                            userTypeId = 1,
                            username = "Raina_Krajcik"
                        });
                });

            modelBuilder.Entity("eventManagementAPI.Models.UserType", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_type_description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("user_type_name");

                    b.HasKey("id");

                    b.ToTable("user_types", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            description = "User with full administrative rights",
                            name = "Administrator"
                        },
                        new
                        {
                            id = 2,
                            description = "User with read-only access",
                            name = "Viewer"
                        });
                });

            modelBuilder.Entity("eventManagementAPI.Models.User", b =>
                {
                    b.HasOne("eventManagementAPI.Models.UserType", "userType")
                        .WithMany("users")
                        .HasForeignKey("userTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userType");
                });

            modelBuilder.Entity("eventManagementAPI.Models.UserType", b =>
                {
                    b.Navigation("users");
                });
#pragma warning restore 612, 618
        }
    }
}
